# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\"!\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"(\n\x0bTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"\x1f\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x08TaskList\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"\x14\n\x06TaskId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2{\n\x0bTaskService\x12&\n\x07\x41\x64\x64Task\x12\x0c.TaskRequest\x1a\r.TaskResponse\x12\x1e\n\tListTasks\x12\x06.Empty\x1a\t.TaskList\x12$\n\nDeleteTask\x12\x07.TaskId\x1a\r.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=15
  _globals['_TASK']._serialized_end=48
  _globals['_TASKREQUEST']._serialized_start=50
  _globals['_TASKREQUEST']._serialized_end=90
  _globals['_TASKRESPONSE']._serialized_start=92
  _globals['_TASKRESPONSE']._serialized_end=123
  _globals['_TASKLIST']._serialized_start=125
  _globals['_TASKLIST']._serialized_end=157
  _globals['_TASKID']._serialized_start=159
  _globals['_TASKID']._serialized_end=179
  _globals['_EMPTY']._serialized_start=181
  _globals['_EMPTY']._serialized_end=188
  _globals['_TASKSERVICE']._serialized_start=190
  _globals['_TASKSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
